export const projects = [
  {
    title: 'Free Lunch Backend',
    description: "Free lunch app that fosters team engagement by facilitating meal sharing.",
    image: 'https://uzo-felix.github.io/myPortfolio/images/freeLunch.jpg',
    tags: ['nodeJs,', 'MySQL,', 'prisma,','swagger ui'],
    source: 'https://github.com/Uzo-Felix/free_lunch_backend',
    visit: 'https://dust-shoulder-1b6.notion.site/Free-Lunch-Endpoint-27e5aa7bfd2a42788100fe93edde9cd5?pvs=4',
    id: 10,
  },
  {
    title: 'Learning Management System',
    description: "LMS app that helps students Streamline, engage, and master tech courses effortlessly online.",
    image: 'https://uzo-felix.github.io/myPortfolio/images/lampnet.PNG',
    tags: ['React, Redux, webPack, NodeJs, MySQL, SpringBoot, Hibernate'],
    source: 'https://github.com/Uzo-Felix/private_repos/blob/main/README.md',
    visit: 'http://lms.lampnetinstitute.com/',
    id: 9,
  },
  {
    title: 'Event Backend',
    description: "Robust backend for event, user management. Built with NodeJs, Typescript, Prisma, PostgreSQL. Seamless event creation, registration, attendee management.",
    image: 'https://uzo-felix.github.io/myPortfolio/images/events2.PNG',
    tags: ['NodeJs, Typescript, PostgreSQL, Prisma'],
    source: 'https://github.com/Uzo-Felix/Events-Backend',
    visit: 'https://github.com/Uzo-Felix/Events-Backend',
    id: 8,
  },
  {
    title: 'Nebo Ascending ventures',
    description: "Nebo Ascending: Thrifting, lending for urgent cash needs. Low interest, flexible repayment.",
    image: 'https://uzo-felix.github.io/myPortfolio/images/image.png',
    tags: ['React, Material UI, NodeJs, PostgreSQL, sequelize'],
    source: 'https://github.com/Uzo-Felix/private_repos/blob/main/README.md',
    visit: 'https://www.nebo.com.ng/',
    id: 7,
  },
  {
    title: 'My Blog-Post',
    description: "A fullstack blog app where user can read, create and edit blog post",
    image: 'https://uzo-felix.github.io/myPortfolio/images/blog.PNG',
    tags: ['React,', 'Mongodb,', 'nodeJs,', 'JWT,', 'AWS cloud Storage'],
    source: 'https://github.com/Uzo-Felix/blog-App/tree/cleanUp',
    visit: 'https://felix-blog-jhxt4i6s0-uzo-felix.vercel.app/',
    id: 6,
  },
  {
    title: 'Maximum Luxury',
    description: "We partake in construction and development processes from start to finish by providing real estate development solutions to our clients.",
    image: 'https://uzo-felix.github.io/myPortfolio/images/maxluxury.png',
    tags: ['React, Sanity CMS, EmailJs'],
    source: 'https://github.com/Uzo-Felix/private_repos/blob/main/README.md',
    visit: 'https://maximumluxury.com.ng/',
    id: 7,
  },
  {
    title: 'Ecommerce',
    description: "A modern ecommerce app with nextjs, mongodb for database and stripe for payments",
      image: 'https://uzo-felix.github.io/myPortfolio/images/Capture.PNG',
      tags: ['React','Nextjs', 'Tailwindcss', 'Mongodb','Stripe'],
    source: 'https://github.com/Uzo-Felix/ecommerce',
    visit: 'https://ecommerce-muy6-8d2ui7ite-uzo-felix.vercel.app/',
    id: 11,
  },
  {
    title: 'Gpt-3',
    description: "Beautifully designed and highly responsive ui/ux React application transformed from figma design",
      image: 'https://uzo-felix.github.io/myPortfolio/images/gpt3.PNG',
      tags: ['React', 'figma'],
    source: 'https://github.com/Uzo-Felix/gpt-3_Felix',
    visit: 'https://uzo-felix.github.io/gpt3/',
    id: 1,
  },
  {
    title: 'Bank App',
    description: "Figma design transformed into react app",
    image: 'https://uzo-felix.github.io/myPortfolio/images/bank.PNG',
    tags: ['React', 'Vite', 'Tailwind'],
    source: 'https://github.com/Uzo-Felix/bank',
    visit: 'https://uzo-felix.github.io/bank',
    id: 2,
  },
  {
    title: 'Restaurant',
    description: "Figma design transformed into React App",
    image: 'https://uzo-felix.github.io/myPortfolio/images/restaurant.PNG',
    tags: ['React', 'Figma'],
    source: 'https://github.com/Uzo-Felix/restaurant',
    visit: 'https://uzo-felix.github.io/restaurant',
    id: 3,
  },
  {
    title: 'Portfolio',
    description: "Figma design transformed into nextJs app",
    image: 'https://uzo-felix.github.io/myPortfolio/images/portfolio.PNG',
    tags: ['NextJs'],
    source: 'https://github.com/Uzo-Felix/myPortfolio',
    visit: 'https://uzo-felix.github.io/myPortfolio',
    id: 4,
  },
  {
    title: 'Restiful Api',
    description: "Student Management API built with node, postgresql and postman",
    image: 'https://uzo-felix.github.io/myPortfolio/images/postgres-logo-1.png',
    tags: ['node', 'postgresql', 'expressJs'],
    source: 'https://github.com/Uzo-Felix/restApi',
    visit: 'https://github.com/Uzo-Felix/restApi',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2022, text: 'Fullstack Intern at IGHub', },
  { year: 2023, text: 'Software Engineer at Alx Africa', },
  { year: 2023, text: 'Software Engineer at Lampnet solutions', },
];