export const projects = [
  {
    title: 'Ecommerce',
    description: "A modern fullstack ecommerce app with nextjs, mongodb for database and stripe for payments",
      image: 'https://uzo-felix.github.io/myPortfolio/images/Capture.PNG',
      tags: ['React','Nextjs', 'Tailwindcss', 'Mongodb','Stripe'],
    source: 'https://github.com/Uzo-Felix/ecommerce',
    visit: 'https://ecommerce-muy6-8d2ui7ite-uzo-felix.vercel.app/',
    id: 0,
  },
  {
    title: 'Gpt-3',
    description: "Beautifully designed and highly responsive ui/ux React application transformed from figma design",
      image: 'https://uzo-felix.github.io/myPortfolio/images/gpt3.PNG',
      tags: ['React', 'figma'],
    source: 'https://github.com/Uzo-Felix/gpt-3_Felix',
    visit: 'https://uzo-felix.github.io/gpt3/',
    id: 1,
  },
  {
    title: 'Bank App',
    description: "Figma design transformed into react app",
    image: 'https://uzo-felix.github.io/myPortfolio/images/bank.PNG',
    tags: ['React', 'Vite', 'Tailwind'],
    source: 'https://github.com/Uzo-Felix/bank',
    visit: 'https://uzo-felix.github.io/bank',
    id: 2,
  },
  {
    title: 'Restaurant',
    description: "Figma design transformed into React App",
    image: 'https://uzo-felix.github.io/myPortfolio/images/restaurant.PNG',
    tags: ['React', 'Figma'],
    source: 'https://github.com/Uzo-Felix/restaurant',
    visit: 'https://uzo-felix.github.io/restaurant',
    id: 3,
  },
  {
    title: 'Portfolio',
    description: "Figma design transformed into nextJs app",
    image: 'https://uzo-felix.github.io/myPortfolio/images/portfolio.PNG',
    tags: ['NextJs'],
    source: 'https://github.com/Uzo-Felix/myPortfolio',
    visit: 'https://uzo-felix.github.io/myPortfolio',
    id: 4,
  },
  {
    title: 'Restiful Api',
    description: "Restful API built with node, postgresql and postman",
    image: 'https://uzo-felix.github.io/myPortfolio/images/postgres-logo-1.png',
    tags: ['node', 'postgresql', 'expressJs'],
    source: 'https://github.com/Uzo-Felix/restApi',
    visit: 'https://github.com/Uzo-Felix/restApi',
    id: 5,
  },
  {
    title: 'My Blog-Post',
    description: "A MERN stack blog app where user can read, create and edit blog post",
    image: 'https://uzo-felix.github.io/myPortfolio/images/blog.PNG',
    tags: ['React,', 'Mongodb,', 'nodeJs,', 'JWT,', 'AWS cloud Storage'],
    source: 'https://github.com/Uzo-Felix/Blog-app',
    visit: 'https://github.com/Uzo-Felix/Blog-app',
    id: 6,
  },
];

export const TimeLineData = [
  { year: 2022, text: 'Started my journey', },
];